spring.application.name=backend

# Database
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:eduvault_db}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:@dhruv123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# File Upload
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
file.upload-dir=${FILE_UPLOAD_DIR:/home/dhruv/eduvault-files}
spring.data.web.pageable.serialization-mode=via-dto
# Allow files up to 20MB to match the React frontend

# JWT
jwt.secret=${JWT_SECRET:eduvault-secret-key-must-be-at-least-32-characters-long}
jwt.expiration=${JWT_EXPIRATION:2592000000}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dpbs2obqm}
cloudinary.api-key=${CLOUDINARY_API_KEY:499828566725986}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:FzwfovJnKrXZlprb8BVJ0m7dsdA}

# Reduce memory usage
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.jpa.open-in-view=false
server.tomcat.threads.max=10
server.tomcat.threads.min-spare=2

# Server
server.port=${PORT:8080}